
/*Guidance is internal.
12...
11...
10...
9...
8...
7...
Ignition sequence start.
6...
5...
4...
3...
2...
1...
All engine running.
Lift off on Apollo 11!*/
public class Apollo{
  public static void main(String[] args) {
    System.out.println("Guidance is internal.");
    for (int i=12;i>=1;i--){
      System.out.println(i+"...");
      if(i==7){
        System.out.println("Ignition sequence start.");
      }
    }
    System.out.println("All engine running.");
    System.out.println("Lift off on Apollo 11!");
  }
}
